import { defaultLevers, type LeverValues } from '@/sim/levers'

/** Resource- and energy-limited meadow. See docs/validation.md for measured survival. */
export const STABLE_PRESET: LeverValues = {
  ...defaultLevers(),
  'prey.initial': 160,
  'pred.initial': 6,
  'prey.adultAge': 50,
  'prey.birthGap': 90,
  'prey.litter': 2,
  'prey.lifespan': 840,
  'prey.breedEnergy': 0.65,
  'prey.childEnergy': 0.45,
  'prey.maxEnergy': 180,
  'prey.metabolism': 0.35,
  'prey.speedCost': 0.5,
  'prey.mealEnergy': 55,
  'prey.speed': 1.25,
  'prey.sense': 1,
  'prey.turn': 1,
  'pred.adultAge': 130,
  'pred.birthGap': 350,
  'pred.litter': 1,
  'pred.lifespan': 1000,
  'pred.breedEnergy': 0.95,
  'pred.childEnergy': 0.6,
  'pred.maxEnergy': 240,
  'pred.metabolism': 0.15,
  'pred.speedCost': 0.9,
  'pred.mealEnergy': 90,
  'pred.speed': 1,
  'pred.sense': 1.3,
  'pred.turn': 1,
  'food.patches': 19,
  'food.stock': 30,
  'food.regrow': 9,
  'food.sprout': 2,
  'habitat.cover': 8,
  'evo.mutation': 0.03,
}
